### PR TITLE
Prepare release v2.0.5

### PR DESCRIPTION
**Pull request by WanzenBug**

### CODE REVIEW

**Comment by WanzenBug** [comment]
Apparently we now get distributions with name `None` on Python 3.7/3.8 🤦

**Review by fphammerle — APPROVED** [review]

**Comment by fphammerle** [comment]
release https://pypi.org/project/pylint-import-requirements/2.0.5/

thanks! :)

**Comment by fphammerle** [comment]
> Apparently we now get distributions with name `None` on Python 3.7/3.8 facepalm

false positive warnings? or just internally?

**Comment by fphammerle** [comment]
> > Apparently we now get distributions with name `None` on Python 3.7/3.8 facepalm
> 
> false positive warnings? or just internally?

sorry, now I get it: https://travis-ci.com/github/WanzenBug/pylint-import-requirements/jobs/379579998#L331

**Comment by fphammerle** [comment]
master is green though :joy:

https://travis-ci.com/github/WanzenBug/pylint-import-requirements/builds/182121649

**Pull request merged**
