### PR TITLE
skip imports via custom loaders not setting origin field module's spec

### LINKED ISSUE #18: support for import statements invoking custom loaders like PyGObject's gi.importer.DynamicImporter
```python
$ pipenv run pylint --load-plugins=pylint_import_requirements systemctl_mqtt
************* Module systemctl_mqtt
[...]
Traceback (most recent call last):
  File "/home/runner/.local/share/virtualenvs/systemctl-mqtt-UQbfQXT6/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/home/runner/.local/share/virtualenvs/systemctl-mqtt-UQbfQXT6/lib/python3.7/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/home/runner/.local/share/virtualenvs/systemctl-mqtt-UQbfQXT6/lib/python3.7/site-packages/pylint/lint/run.py", line 344, in __init__
    linter.check(args)
  File "/home/runner/.local/share/virtualenvs/systemctl-mqtt-UQbfQXT6/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 871, in check
    self.get_ast, self._iterate_file_descrs(files_or_modules)
  File "/home/runner/.local/share/virtualenvs/systemctl-mqtt-UQbfQXT6/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 904, in _check_files
    self._check_file(get_ast, check_astroid_module, name, filepath, modname)
  File "/home/runner/.local/share/virtualenvs/systemctl-mqtt-UQbfQXT6/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 930, in _check_file
    check_astroid_module(ast_node)
  File "/home/runner/.local/share/virtualenvs/systemctl-mqtt-UQbfQXT6/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 1063, in check_astroid_module
    ast_node, walker, rawcheckers, tokencheckers
  File "/home/runner/.local/share/virtualenvs/systemctl-mqtt-UQbfQXT6/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 1107, in _check_astroid_module
    walker.walk(ast_node)
  File "/home/runner/.local/share/virtualenvs/systemctl-mqtt-UQbfQXT6/lib/python3.7/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  File "/home/runner/.local/share/virtualenvs/systemctl-mqtt-UQbfQXT6/lib/python3.7/site-packages/pylint/utils/ast_walker.py", line 72, in walk
    callback(astroid)
  File "/home/runner/.local/share/virtualenvs/systemctl-mqtt-UQbfQXT6/lib/python3.7/site-packages/pylint_import_requirements/__init__.py", line 154, in visit_import
    self.check_import(node, modname)
  File "/home/runner/.local/share/virtualenvs/systemctl-mqtt-UQbfQXT6/lib/python3.7/site-packages/pylint_import_requirements/__init__.py", line 215, in check_import
    self.check_namespace_module(node, spec, names)
  File "/home/runner/.local/share/virtualenvs/systemctl-mqtt-UQbfQXT6/lib/python3.7/site-packages/pylint_import_requirements/__init__.py", line 252, in check_namespace_module
    submodule_path = str(next(iter(spec.submodule_search_locations)))
TypeError: 'NoneType' object is not iterable
```

introduced by this comment: https://github.com/fphammerle/systemctl-mqtt/commit/dff96fc3a8636a8507464f1594afdd8f73e40dbc

```diff
diff --git a/setup.py b/setup.py
index 8c87ad4..2270c39 100644
--- a/setup.py
+++ b/setup.py
@@ -62,7 +62,7 @@ setuptools.setup(
     ],
     entry_points={"console_scripts": ["systemctl-mqtt = systemctl_mqtt:_main",]},
     # https://dbus.freedesktop.org/doc/dbus-python/news.html
-    install_requires=["dbus-python<2", "paho-mqtt<2"],
+    install_requires=["PyGObject<4", "dbus-python<2", "paho-mqtt<2"],
     setup_requires=["setuptools_scm"],
     tests_require=["pytest"],
 )
diff --git a/systemctl_mqtt/__init__.py b/systemctl_mqtt/__init__.py
index 8b00cac..956d718 100644
--- a/systemctl_mqtt/__init__.py
+++ b/systemctl_mqtt/__init__.py
@@ -24,6 +24,8 @@ import socket
 import typing
 
 import dbus
+# https://pygobject.readthedocs.io/en/latest/getting_started.html#ubuntu-logo-ubuntu-debian-logo-debian
+import gi.repository.GLib
 
 import paho.mqtt.client
[...]
```

### PR DESCRIPTION
**Pull request by fphammerle**
https://github.com/WanzenBug/pylint-import-requirements/issues/18#issuecomment-646471080

### CODE REVIEW

**Comment by fphammerle** [comment]
python version mismatch:
```
[...]
$ source ~/virtualenv/python3.6/bin/activate
$ python --version
Python 3.6.7
$ pip --version
pip 19.0.3 from /home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pip (python 3.6)
install.1
0.67s$ pip install --upgrade 'pipenv>=2018.10.9,<v2020.5.28'
install.2
23.78s$ pipenv sync --dev
Creating a virtualenv for this project…
Pipfile: /home/travis/build/WanzenBug/pylint-import-requirements/Pipfile
Using /opt/pyenv/versions/3.7/bin/python3.7m (3.7.1) to create virtualenv…
[...]
```

**Comment by fphammerle** [comment]
versions in `Pipfile.lock` do not comply with version constraints in `Pipfile`

**Comment by fphammerle** [comment]
PR on hold until https://github.com/WanzenBug/pylint-import-requirements/pull/20 is fixed

**Review by WanzenBug — APPROVED** [review]

**Comment by WanzenBug** [comment]
Thanks! I'll release a new version soon

**Comment by fphammerle** [comment]
Great! Thanks :)

**Pull request merged**
